### ISSUE TITLE
Remote JMX (and nodetool usage) disabled in latest STUPS Cassandra

### ISSUE THREAD

**Issue by vosmann** [zalando/stups-cassandra#10]
Recently, a cassandra-env.sh file was added. Unfortunately, it also contained default settings appropriate only for running and testing Cassandra locally.
Nodes started with this setting do not listen on the JMX port (7199) and can’t be examined with nodetool. In the logs this manifests itself as:
	
    WARN 22:36:38 JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info. 

We need to re-enable remote JMX connections.
The current version, `registry.opensource.zalan.do/mop/stups-cassandra:2.1.9-p0`, contains this faulty cassandra-env.sh, so we might want to deprecate that image. 

Perhaps we can also give cassandra-env.sh another review together.

**Comment by vosmann** [comment]
Well, it seems to be by design for security reasons.

**Comment by MALPI** [comment]
Hey, thanks for reporting. Actually I don't think that remote JMX access is needed. Indeed for security reasons I think it's better to keep it disabled. What do you think @lmineiro?

**Comment by vosmann** [comment]
For the time being let's keep it local-only. Closing the issue.
