### ISSUE TITLE
No cassandra logs in application.log

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando/stups-cassandra#20]
When we start the appliance, we see only supervisord logs in `/var/log/application.log` and scalyr (`cassandra entered RUNNING state`), we don't see any log output from startup script and/or cassandra itself

**Comment by MALPI** [comment]
Hey, atually the logs are saved under '/var/log/supervisor' since cassandra is running as a child process by it and it's taking care for it.

I'll change that tomorrow.

**Comment by MALPI** [comment]
emove the `-Dcassandra.logdir=/var/cassandra/log` in the startup script And check whether log rotation is working or not.

**Comment by CVirus** [comment]
Log rotation works properly.. I was mistaken.
