### ISSUE TITLE
The backup script doesn't seem to work.

### ISSUE THREAD

**Issue by amjedonline** [zalando/stups-cassandra#7]
1. Fails when run with dash shell
2. snapshots are not cleaned
3. Wrong directory structure backed up (includes the actual data files).
4. and other minor issues.

**Comment by MALPI** [comment]
As already said, currently I've no time to check this. But as soon as I have I will have a look.

**Comment by lmineiro** [comment]
How does the dash shell come into this picture? The appliance's docker image as defined will use bash and the backup scripts also depend only on /bin/bash. Can you elaborate?

**Comment by lmineiro** [comment]
Also, would you be so kind to create separate issues for "other minor issues"?

**Comment by MALPI** [comment]
Actually, the reason why the scripts don't work in your environment is that you're using dash... With point 2 you're right but it's not really an issue, since these are symlinks only anyway.

**Comment by MALPI** [comment]
The issue will be fixed with PR #26
