### ISSUE TITLE
Logging Configuration

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/stups-cassandra#9]
It looks like this appliance uses the default `logback.xml` of Cassandra. This configuration writes to `stdout` and a file (in `cassandra.logdir`). It might be better to have a custom configuration which only writes to `stdout`.

See configuration [here](https://github.com/apache/cassandra/blob/cassandra-2.1.11/conf/logback.xml).

**Comment by hjacobs** [comment]
:+1:
